### ISSUE TITLE
Write Skeleton Smart Contract

### ISSUE THREAD

**Issue by AlvaroLuken** [hacknyu-team-ethereum/great-ether#1]

**Comment by Skyge** [comment]
One transaction, one contract?
And what will we want to achieve in the contract?

**Comment by AlvaroLuken** [comment]
@Skyge hey! how did you come across this project?

**Comment by Skyge** [comment]
@AlvaroLuken Just from the Gitter.

**Comment by AlvaroLuken** [comment]
@Skyge oh hey sorry, that's right! We are trying to achieve a simple peer to peer transaction using a smart contract... yes it will be one transaction one contract. In it we are trying to write functionality so that ETH-USD conversion takes place inside the contract - we'd love any suggestions/opinions!

**Comment by Skyge** [comment]
@AlvaroLuken OK, I made a PR just now.
